uint64 timestamp    # time since system start (microseconds)

float32 thrust_error1
float32 thrust_error2
float32 thrust_error3
float32 thrust_error4
float32 thrust_control_out1
float32 thrust_control_out2
float32 thrust_control_out3
float32 thrust_control_out4
float32 thrust_desired1
float32 thrust_desired2
float32 thrust_desired3
float32 thrust_desired4

float32 thrust_control_out_pwm1
float32 thrust_control_out_pwm2
float32 thrust_control_out_pwm3
float32 thrust_control_out_pwm4

float32 thrust_start

float32 kp
float32 ki
float32 kd

# TOPICS thrust_control_data