/****************************************************************************
 *
 *   Copyright (c) 2012-2018 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/**
 * @file mixer_multirotor.cpp
 *
 * Multi-rotor mixers.
 */

#include "MultirotorMixer.hpp"

#include <float.h>
#include <cstring>
#include <cstdio>

#include <mathlib/mathlib.h>

#ifdef MIXER_MULTIROTOR_USE_MOCK_GEOMETRY
enum class MultirotorGeometry : MultirotorGeometryUnderlyingType {
	QUAD_X,
	MAX_GEOMETRY
};
namespace
{
const MultirotorMixer::Rotor _config_quad_x[] = {
	{ -0.707107,  0.707107,  1.000000,  1.000000 },
	{  0.707107, -0.707107,  1.000000,  1.000000 },
	{  0.707107,  0.707107, -1.000000,  1.000000 },
	{ -0.707107, -0.707107, -1.000000,  1.000000 },
};
const MultirotorMixer::Rotor *_config_index[] = {
	&_config_quad_x[0]
};
const unsigned _config_rotor_count[] = {4};
const char *_config_key[] = {"4x"};
}

#else

// This file is generated by the px_generate_mixers.py script which is invoked during the build process
// #include "mixer_multirotor.generated.h"
#include "mixer_multirotor_normalized.generated.h"

#endif /* MIXER_MULTIROTOR_USE_MOCK_GEOMETRY */


#define debug(fmt, args...)	do { } while(0)
//#define debug(fmt, args...)	do { printf("[mixer] " fmt "\n", ##args); } while(0)
//#include <debug.h>
//#define debug(fmt, args...)	syslog(fmt "\n", ##args)

MultirotorMixer::MultirotorMixer(ControlCallback control_cb, uintptr_t cb_handle, MultirotorGeometry geometry) :
	MultirotorMixer(control_cb, cb_handle, _config_index[(int)geometry], _config_rotor_count[(int)geometry])
{
}

MultirotorMixer::MultirotorMixer(ControlCallback control_cb, uintptr_t cb_handle, const Rotor *rotors,
				 unsigned rotor_count) :
	Mixer(control_cb, cb_handle),
	_rotor_count(rotor_count),
	_rotors(rotors),
	_outputs_prev(new float[_rotor_count]),
	_tmp_array(new float[_rotor_count])
{
	for (unsigned i = 0; i < _rotor_count; ++i) {
		_outputs_prev[i] = -1.f;
	}
}

MultirotorMixer::~MultirotorMixer()
{
	delete[] _outputs_prev;
	delete[] _tmp_array;
}

MultirotorMixer *
MultirotorMixer::from_text(Mixer::ControlCallback control_cb, uintptr_t cb_handle, const char *buf, unsigned &buflen)
{
	MultirotorGeometry geometry = MultirotorGeometry::MAX_GEOMETRY;
	char geomname[16];

	/* enforce that the mixer ends with a new line */
	if (!string_well_formed(buf, buflen)) {
		return nullptr;
	}

	if (sscanf(buf, "R: %15s", geomname) != 1) {
		debug("multirotor parse failed on '%s'", buf);
		return nullptr;
	}

	buf = skipline(buf, buflen);

	if (buf == nullptr) {
		debug("no line ending, line is incomplete");
		return nullptr;
	}

	debug("remaining in buf: %d, first char: %c", buflen, buf[0]);

	for (MultirotorGeometryUnderlyingType i = 0; i < (MultirotorGeometryUnderlyingType)MultirotorGeometry::MAX_GEOMETRY;
	     i++) {
		if (!strcmp(geomname, _config_key[i])) {
			geometry = (MultirotorGeometry)i;
			break;
		}
	}

	if (geometry == MultirotorGeometry::MAX_GEOMETRY) {
		debug("unrecognised geometry '%s'", geomname);
		return nullptr;
	}

	debug("adding multirotor mixer '%s'", geomname);

	return new MultirotorMixer(control_cb, cb_handle, geometry);
}

float
MultirotorMixer::compute_desaturation_gain(const float *desaturation_vector, const float *outputs,
		saturation_status &sat_status, float min_output, float max_output) const
{
	float k_min = 0.f;
	float k_max = 0.f;

	for (unsigned i = 0; i < _rotor_count; i++) {
		// Avoid division by zero. If desaturation_vector[i] is zero, there's nothing we can do to unsaturate anyway
		if (fabsf(desaturation_vector[i]) < FLT_EPSILON) {
			continue;
		}

		if (outputs[i] < min_output) {
			float k = (min_output - outputs[i]) / desaturation_vector[i];

			if (k < k_min) { k_min = k; }

			if (k > k_max) { k_max = k; }

			sat_status.flags.motor_neg = true;
		}

		if (outputs[i] > max_output) {
			float k = (max_output - outputs[i]) / desaturation_vector[i];

			if (k < k_min) { k_min = k; }

			if (k > k_max) { k_max = k; }

			sat_status.flags.motor_pos = true;
		}
	}

	// Reduce the saturation as much as possible
	return k_min + k_max;
}

void
MultirotorMixer::minimize_saturation(const float *desaturation_vector, float *outputs,
				     saturation_status &sat_status, float min_output, float max_output, bool reduce_only) const
{
	float k1 = compute_desaturation_gain(desaturation_vector, outputs, sat_status, min_output, max_output);

	if (reduce_only && k1 > 0.f) {
		return;
	}

	for (unsigned i = 0; i < _rotor_count; i++) {
		outputs[i] += k1 * desaturation_vector[i];
	}

	// Compute the desaturation gain again based on the updated outputs.
	// In most cases it will be zero. It won't be if max(outputs) - min(outputs) > max_output - min_output.
	// In that case adding 0.5 of the gain will equilibrate saturations.
	float k2 = 0.5f * compute_desaturation_gain(desaturation_vector, outputs, sat_status, min_output, max_output);

	for (unsigned i = 0; i < _rotor_count; i++) {
		outputs[i] += k2 * desaturation_vector[i];
	}
}

void
MultirotorMixer::mix_airmode_rp(float roll, float pitch, float yaw, float thrust, float *outputs)
{
	// Airmode for roll and pitch, but not yaw

	// Mix without yaw
	for (unsigned i = 0; i < _rotor_count; i++) {
		outputs[i] = roll * _rotors[i].roll_scale +
			     pitch * _rotors[i].pitch_scale +
			     thrust * _rotors[i].thrust_scale;

		// Thrust will be used to unsaturate if needed
		_tmp_array[i] = _rotors[i].thrust_scale;
	}

	minimize_saturation(_tmp_array, outputs, _saturation_status);

	// Mix yaw independently
	mix_yaw(yaw, outputs);
}

/*
	混控矩阵
	const MultirotorMixer::Rotor _config_quad_x[] = {
		{ -0.707107,  0.707107,  1.000000,  1.000000 },
		{  0.707107, -0.707107,  1.000000,  1.000000 },
		{  0.707107,  0.707107, -1.000000,  1.000000 },
		{ -0.707107, -0.707107, -1.000000,  1.000000 },
*/
void
MultirotorMixer::mix_airmode_rpy(float roll, float pitch, float yaw, float thrust, float *outputs)
{
	// Airmode for roll, pitch and yaw

	// Do full mixing
	for (unsigned i = 0; i < _rotor_count; i++) 
	{
		// outputs[i]为各轴旋翼所需的期望升力
		outputs[i] = roll * _rotors[i].roll_scale + // 混控矩阵中的第i行第一个元素
			     pitch * _rotors[i].pitch_scale + // 混控矩阵中的第i行第二个元素
			     yaw * _rotors[i].yaw_scale + // 混控矩阵中的第i行第三个元素
			     thrust * _rotors[i].thrust_scale; // 混控矩阵中的第i行第四个元素

		// Thrust will be used to unsaturate if needed
		_tmp_array[i] = _rotors[i].thrust_scale;
	}

	minimize_saturation(_tmp_array, outputs, _saturation_status);

	// Unsaturate yaw (in case upper and lower bounds are exceeded)
	// to prioritize roll/pitch over yaw.
	for (unsigned i = 0; i < _rotor_count; i++) 
	{
		_tmp_array[i] = _rotors[i].yaw_scale;
	}

	minimize_saturation(_tmp_array, outputs, _saturation_status);
}

void
MultirotorMixer::mix_airmode_disabled(float roll, float pitch, float yaw, float thrust, float *outputs)
{
	// Airmode disabled: never allow to increase the thrust to unsaturate a motor

	// Mix without yaw
	for (unsigned i = 0; i < _rotor_count; i++) {
		outputs[i] = roll * _rotors[i].roll_scale +
			     pitch * _rotors[i].pitch_scale +
			     thrust * _rotors[i].thrust_scale;

		// Thrust will be used to unsaturate if needed
		_tmp_array[i] = _rotors[i].thrust_scale;
	}

	// only reduce thrust
	minimize_saturation(_tmp_array, outputs, _saturation_status, 0.f, 1.f, true);

	// Reduce roll/pitch acceleration if needed to unsaturate
	for (unsigned i = 0; i < _rotor_count; i++) {
		_tmp_array[i] = _rotors[i].roll_scale;
	}

	minimize_saturation(_tmp_array, outputs, _saturation_status);

	for (unsigned i = 0; i < _rotor_count; i++) {
		_tmp_array[i] = _rotors[i].pitch_scale;
	}

	minimize_saturation(_tmp_array, outputs, _saturation_status);

	// Mix yaw independently
	mix_yaw(yaw, outputs);
}

void MultirotorMixer::mix_yaw(float yaw, float *outputs)
{
	// Add yaw to outputs
	for (unsigned i = 0; i < _rotor_count; i++) {
		outputs[i] += yaw * _rotors[i].yaw_scale;

		// Yaw will be used to unsaturate if needed
		_tmp_array[i] = _rotors[i].yaw_scale;
	}

	// Change yaw acceleration to unsaturate the outputs if needed (do not change roll/pitch),
	// and allow some yaw response at maximum thrust
	minimize_saturation(_tmp_array, outputs, _saturation_status, 0.f, 1.15f);

	for (unsigned i = 0; i < _rotor_count; i++) {
		_tmp_array[i] = _rotors[i].thrust_scale;
	}

	// reduce thrust only
	minimize_saturation(_tmp_array, outputs, _saturation_status, 0.f, 1.f, true);
}

// unsigned
// MultirotorMixer::mix(float *outputs, unsigned space)
// {
	
// 	if (space < _rotor_count) 
// 	{
// 		return 0;
// 	}

// 	float roll    = math::constrain(get_control(0, 0), -1.0f, 1.0f);
// 	float pitch   = math::constrain(get_control(0, 1), -1.0f, 1.0f);
// 	float yaw     = math::constrain(get_control(0, 2), -1.0f, 1.0f);
// 	float thrust  = math::constrain(get_control(0, 3), 0.0f, 1.0f);

// 	// clean out class variable used to capture saturation
// 	_saturation_status.value = 0;

// 	// Do the mixing using the strategy given by the current Airmode configuration
// 	switch (_airmode) 
// 	{
// 	case Airmode::roll_pitch:
// 		mix_airmode_rp(roll, pitch, yaw, thrust, outputs);
// 		break;

// 	case Airmode::roll_pitch_yaw:
// 		mix_airmode_rpy(roll, pitch, yaw, thrust, outputs);
// 		break;

// 	case Airmode::disabled:
// 	default: // just in case: default to disabled
// 		mix_airmode_disabled(roll, pitch, yaw, thrust, outputs);
// 		break;
// 	}

// 	// Apply thrust model and scale outputs to range [idle_speed, 1].
// 	// At this point the outputs are expected to be in [0, 1], but they can be outside, for example
// 	// if a roll command exceeds the motor band limit.
// 	for (unsigned i = 0; i < _rotor_count; i++) 
// 	{
// 		// Implement simple model for static relationship between applied motor pwm and motor thrust
// 		// model: thrust = (1 - _thrust_factor) * PWM + _thrust_factor * PWM^2
// 		if (_thrust_factor > 0.0f) 
// 		{
// 			outputs[i] = -(1.0f - _thrust_factor) / (2.0f * _thrust_factor) + sqrtf((1.0f - _thrust_factor) *
// 					(1.0f - _thrust_factor) / (4.0f * _thrust_factor * _thrust_factor) + (outputs[i] < 0.0f ? 0.0f : outputs[i] /
// 							_thrust_factor));
// 		}
// 		outputs[i] = math::constrain((2.f * outputs[i] - 1.f), -1.f, 1.f);
// 	}

// 	// Slew rate limiting and saturation checking
// 	for (unsigned i = 0; i < _rotor_count; i++) 
// 	{
// 		bool clipping_high = false;
// 		bool clipping_low_roll_pitch = false;
// 		bool clipping_low_yaw = false;

// 		// Check for saturation against static limits.
// 		// We only check for low clipping if airmode is disabled (or yaw
// 		// clipping if airmode==roll/pitch), since in all other cases thrust will
// 		// be reduced or boosted and we can keep the integrators enabled, which
// 		// leads to better tracking performance.
// 		if (outputs[i] < -0.99f) 
// 		{
// 			if (_airmode == Airmode::disabled) 
// 			{
// 				clipping_low_roll_pitch = true;
// 				clipping_low_yaw = true;

// 			} 
// 			else if (_airmode == Airmode::roll_pitch) 
// 			{
// 				clipping_low_yaw = true;
// 			}
// 		}

// 		// check for saturation against slew rate limits
// 		if (_delta_out_max > 0.0f) 
// 		{
// 			float delta_out = outputs[i] - _outputs_prev[i];

// 			if (delta_out > _delta_out_max) 
// 			{
// 				outputs[i] = _outputs_prev[i] + _delta_out_max;
// 				clipping_high = true;

// 			} 
// 			else if (delta_out < -_delta_out_max) 
// 			{
// 				outputs[i] = _outputs_prev[i] - _delta_out_max;
// 				clipping_low_roll_pitch = true;
// 				clipping_low_yaw = true;
// 			}
// 		}

// 		_outputs_prev[i] = outputs[i];

// 		// update the saturation status report
// 		update_saturation_status(i, clipping_high, clipping_low_roll_pitch, clipping_low_yaw);
// 	}

// 	// this will force the caller of the mixer to always supply new slew rate values, otherwise no slew rate limiting will happen
// 	_delta_out_max = 0.0f;

// 	return _rotor_count;
// }

unsigned
MultirotorMixer::mix(float *outputs, unsigned space)
{
	
	// 如果最大输出通道数（通常为8）小于电机数，返回0
	if (space < _rotor_count) 
	{
		return 0;
	}

	// 订阅力控制数据
	// int thrustcontroldata_sub_fd = orb_subscribe(ORB_ID(thrust_control_data));
	// orb_set_interval(thrustcontroldata_sub_fd, 20);
	_thrust_control_data_sub.update(&thrustcontroldata);
	_robust_control_data_sub.update(&_robust_control_data);

	// px4_pollfd_struct_t fds[] =
	// {
	// 	{ .fd = thrustcontroldata_sub_fd,   .events = POLLIN },
	// };

	// if (fds[0].revents & POLLIN)
    // {
    //     orb_copy(ORB_ID(thrust_control_data), thrustcontroldata_sub_fd, &thrustcontroldata);
    // }

	// 从控制输入获取期望的roll、pitch、yaw和推力。
	// roll、pitch、yaw分别取控制输入组0的第0，1，2个元素经过缩放系数缩放，再进行限幅，
	// 限制在，-1到1之间。推力直接取控制输入组0的第3个元素，并限幅在0到1之间。
	float roll    = math::constrain(get_control(0, 0), -1.0f, 1.0f);
	float pitch   = math::constrain(get_control(0, 1), -1.0f, 1.0f);
	float yaw     = math::constrain(get_control(0, 2), -1.0f, 1.0f);
	float thrust  = math::constrain(get_control(0, 3), 0.0f, 1.0f);

	robust_control_data_pid.pid_desired_total_force = thrust;
	robust_control_data_pid.pid_desired_torque_x = roll;
	robust_control_data_pid.pid_desired_torque_y = pitch;
	robust_control_data_pid.pid_desired_torque_z = yaw;

	// 发布PID期望升力和力矩
	robust_control_data_pid.timestamp = hrt_absolute_time();
	_to_robust_control_data_pid_report.publish(robust_control_data_pid);

	if (_robust_control_data.robust_control_start > 0.5f) 
	{
		// roll   = _robust_control_data.desired_torque_x;
		// pitch  = _robust_control_data.desired_torque_y;
		// yaw    = _robust_control_data.desired_torque_z;
		// // thrust = _robust_control_data.desired_total_force;

		// thrust = _robust_control_data.total_desired_total_force;
		roll   = _robust_control_data.total_desired_torque_x;
		pitch  = _robust_control_data.total_desired_torque_y;
		yaw    = _robust_control_data.total_desired_torque_z;
	}

	// thrustdesireddata.torque_pitch_desired = pitch;

	// clean out class variable used to capture saturation
	// 电机饱和度清零
	_saturation_status.value = 0;

	// Do the mixing using the strategy given by the current Airmode configuration
	// 根据当前airmode配置进行混控
	// 下述一共三种混控方式，对应不同的抗执行器饱和策略，roll_pitch和roll_pitch_yaw都属于
	// 使能airmode的范畴，不同的是roll_pitch仅对横滚和俯仰进行抗执行器饱和处理，而偏航单独混控，
	// roll_pitch_yaw则是对横滚、俯仰、偏航均进行抗执行器饱和处理。
	// disabled表示禁用airmode。
	switch (_airmode) 
	{
	case Airmode::roll_pitch:
		mix_airmode_rp(roll, pitch, yaw, thrust, outputs);
		break;

	case Airmode::roll_pitch_yaw:
		mix_airmode_rpy(roll, pitch, yaw, thrust, outputs);
		break;

	case Airmode::disabled:
	default: // just in case: default to disabled
		mix_airmode_disabled(roll, pitch, yaw, thrust, outputs);
		break;
	}

	// 发布各轴期望升力
	// thrustdesireddata.thrust_desired1 = 0.1f;
	// thrustdesireddata.thrust_desired2 = 0.2f;
	// thrustdesireddata.thrust_desired3 = 0.3f;
	// thrustdesireddata.thrust_desired4 = 0.4f;

	thrustdesireddata.thrust_desired1 = outputs[0];
	thrustdesireddata.thrust_desired2 = outputs[1];
	thrustdesireddata.thrust_desired3 = outputs[2];
	thrustdesireddata.thrust_desired4 = outputs[3];

	// outputs[0] = thrustcontroldata.thrust_control_out1;
	// outputs[0] = math::constrain((2.f * outputs[0] - 1.f), -1.f, 1.f);
	// Apply thrust model and scale outputs to range [idle_speed, 1].
	// At this point the outputs are expected to be in [0, 1], but they can be outside, for example
	// if a roll command exceeds the motor band limit.
	// 应用以下推力模型，通过该推力模型，计算出PWM值
	// 移项并解一元二次方程算出PWM值，如下所示

	// if (_thrust_control_data_sub.update(&thrustcontroldata))
	// {
	// 	outputs[0] = thrustcontroldata.thrust_control_out_pwm1;
	// 	outputs[1] = thrustcontroldata.thrust_control_out_pwm2;
	// 	outputs[2] = thrustcontroldata.thrust_control_out_pwm3;
	// 	outputs[3] = thrustcontroldata.thrust_control_out_pwm4;

	// 	for (unsigned i = 0; i < _rotor_count; i++) 
	// 	{
	// 		outputs[i] = math::constrain((2.f * outputs[i] - 1.f), -1.f, 1.f);
	// 	}
	// }
	// else
	// {
	// 	for (unsigned i = 0; i < _rotor_count; i++) 
	// 	{
	// 		// Implement simple model for static relationship between applied motor pwm and motor thrust
	// 		// model: thrust = (1 - _thrust_factor) * PWM + _thrust_factor * PWM^2
	// 		if (_thrust_factor > 0.0f) 
	// 		{
	// 			outputs[i] = -(1.0f - _thrust_factor) / (2.0f * _thrust_factor) + sqrtf((1.0f - _thrust_factor) *
	// 					(1.0f - _thrust_factor) / (4.0f * _thrust_factor * _thrust_factor) + (outputs[i] < 0.0f ? 0.0f : outputs[i] /
	// 							_thrust_factor));
	// 		}
	// 		// 将PWM值从[0,1]缩放至[-1,1]
	// 		outputs[i] = math::constrain((2.f * outputs[i] - 1.f), -1.f, 1.f);
	// 	}
	// }
	for (unsigned i = 0; i < _rotor_count; i++) 
	{
		// Implement simple model for static relationship between applied motor pwm and motor thrust
		// model: thrust = (1 - _thrust_factor) * PWM + _thrust_factor * PWM^2
		if (_thrust_factor > 0.0f) 
		{
			outputs[i] = -(1.0f - _thrust_factor) / (2.0f * _thrust_factor) + sqrtf((1.0f - _thrust_factor) *
					(1.0f - _thrust_factor) / (4.0f * _thrust_factor * _thrust_factor) + (outputs[i] < 0.0f ? 0.0f : outputs[i] /
							_thrust_factor));
		}
		// 将PWM值从[0,1]缩放至[-1,1]
		outputs[i] = math::constrain((2.f * outputs[i] - 1.f), -1.f, 1.f);
	}

	thrustdesireddata.open_loop_control_output1 = outputs[0];
	thrustdesireddata.open_loop_control_output2 = outputs[1];
	thrustdesireddata.open_loop_control_output3 = outputs[2];
	thrustdesireddata.open_loop_control_output4 = outputs[3];

	if ((thrustcontroldata.thrust_start > 0.5f)&&(thrustcontroldata.thrust_start < 1.5f))
	{
		outputs[0] = thrustcontroldata.thrust_control_out_pwm1;
		outputs[1] = thrustcontroldata.thrust_control_out_pwm2;
		outputs[2] = thrustcontroldata.thrust_control_out_pwm3;
		outputs[3] = thrustcontroldata.thrust_control_out_pwm4;
	}
	else if(thrustcontroldata.thrust_start > 1.6f)
	{
		outputs[0] = thrustcontroldata.thrust_kalman_filter_control_out_pwm1;
		outputs[1] = thrustcontroldata.thrust_kalman_filter_control_out_pwm2;
		outputs[2] = thrustcontroldata.thrust_kalman_filter_control_out_pwm3;
		outputs[3] = thrustcontroldata.thrust_kalman_filter_control_out_pwm4;
	}

	thrustdesireddata.full_process_output1 = outputs[0];
	thrustdesireddata.full_process_output2 = outputs[1];
	thrustdesireddata.full_process_output3 = outputs[2];
	thrustdesireddata.full_process_output4 = outputs[3];
	
	thrustdesireddata.timestamp = hrt_absolute_time();
	_to_thrustdesireddata_report.publish(thrustdesireddata);

	// Slew rate limiting and saturation checking
	// 将最终的输出进行抗负向饱和以及变化速率限幅
	for (unsigned i = 0; i < _rotor_count; i++) 
	{
		// 定义标志位
		bool clipping_high = false;
		bool clipping_low_roll_pitch = false;
		bool clipping_low_yaw = false;

		// Check for saturation against static limits.
		// We only check for low clipping if airmode is disabled (or yaw
		// clipping if airmode==roll/pitch), since in all other cases thrust will
		// be reduced or boosted and we can keep the integrators enabled, which
		// leads to better tracking performance.
		// 这里判断是否需要进行抗下限饱和，并对相关的标志位进行置位
		// 具体的抗饱和操作根据设置，在mix_arimode_rp、mix_airmode_rpy、mix_airmode_disabled中进行。
		if (outputs[i] < -0.99f) 
		{
			if (_airmode == Airmode::disabled) 
			{
				clipping_low_roll_pitch = true;
				clipping_low_yaw = true;

			} 
			else if (_airmode == Airmode::roll_pitch) 
			{
				clipping_low_yaw = true;
			}
		}

		// check for saturation against slew rate limits
		// 这里判断每次循环的输出变化幅度是否需要限制，判断方法就是比较当前输出与上一次输出的差值，是否超出极限，
		// 如果超出极限，则设置为最大值，并对标志位进行置位。
		if (_delta_out_max > 0.0f) 
		{
			float delta_out = outputs[i] - _outputs_prev[i];

			if (delta_out > _delta_out_max) 
			{
				outputs[i] = _outputs_prev[i] + _delta_out_max;
				clipping_high = true;

			} 
			else if (delta_out < -_delta_out_max) 
			{
				outputs[i] = _outputs_prev[i] - _delta_out_max;
				clipping_low_roll_pitch = true;
				clipping_low_yaw = true;
			}
		}

		_outputs_prev[i] = outputs[i];

		// update the saturation status report
		// 更新状态标志位
		update_saturation_status(i, clipping_high, clipping_low_roll_pitch, clipping_low_yaw);
	}

	// this will force the caller of the mixer to always supply new slew rate values, otherwise no slew rate limiting will happen
	// 将输出变化幅度的最大值置零，在每次进行混控前都要对该参数进行赋值，否则将不进行限幅。
	_delta_out_max = 0.0f;

	return _rotor_count;
}

/*
 * This function update the control saturation status report using the following inputs:
 *
 * index: 0 based index identifying the motor that is saturating
 * clipping_high: true if the motor demand is being limited in the positive direction
 * clipping_low_roll_pitch: true if the motor demand is being limited in the negative direction (roll/pitch)
 * clipping_low_yaw: true if the motor demand is being limited in the negative direction (yaw)
*/
void
MultirotorMixer::update_saturation_status(unsigned index, bool clipping_high, bool clipping_low_roll_pitch,
		bool clipping_low_yaw)
{
	// The motor is saturated at the upper limit
	// check which control axes and which directions are contributing
	if (clipping_high) {
		if (_rotors[index].roll_scale > 0.0f) {
			// A positive change in roll will increase saturation
			_saturation_status.flags.roll_pos = true;

		} else if (_rotors[index].roll_scale < 0.0f) {
			// A negative change in roll will increase saturation
			_saturation_status.flags.roll_neg = true;
		}

		// check if the pitch input is saturating
		if (_rotors[index].pitch_scale > 0.0f) {
			// A positive change in pitch will increase saturation
			_saturation_status.flags.pitch_pos = true;

		} else if (_rotors[index].pitch_scale < 0.0f) {
			// A negative change in pitch will increase saturation
			_saturation_status.flags.pitch_neg = true;
		}

		// check if the yaw input is saturating
		if (_rotors[index].yaw_scale > 0.0f) {
			// A positive change in yaw will increase saturation
			_saturation_status.flags.yaw_pos = true;

		} else if (_rotors[index].yaw_scale < 0.0f) {
			// A negative change in yaw will increase saturation
			_saturation_status.flags.yaw_neg = true;
		}

		// A positive change in thrust will increase saturation (Z neg is up)
		_saturation_status.flags.thrust_neg = true;
	}

	// The motor is saturated at the lower limit
	// check which control axes and which directions are contributing
	if (clipping_low_roll_pitch) {
		// check if the roll input is saturating
		if (_rotors[index].roll_scale > 0.0f) {
			// A negative change in roll will increase saturation
			_saturation_status.flags.roll_neg = true;

		} else if (_rotors[index].roll_scale < 0.0f) {
			// A positive change in roll will increase saturation
			_saturation_status.flags.roll_pos = true;
		}

		// check if the pitch input is saturating
		if (_rotors[index].pitch_scale > 0.0f) {
			// A negative change in pitch will increase saturation
			_saturation_status.flags.pitch_neg = true;

		} else if (_rotors[index].pitch_scale < 0.0f) {
			// A positive change in pitch will increase saturation
			_saturation_status.flags.pitch_pos = true;
		}

		// A negative change in thrust will increase saturation (Z pos is down)
		_saturation_status.flags.thrust_pos = true;
	}

	if (clipping_low_yaw) {
		// check if the yaw input is saturating
		if (_rotors[index].yaw_scale > 0.0f) {
			// A negative change in yaw will increase saturation
			_saturation_status.flags.yaw_neg = true;

		} else if (_rotors[index].yaw_scale < 0.0f) {
			// A positive change in yaw will increase saturation
			_saturation_status.flags.yaw_pos = true;
		}
	}

	_saturation_status.flags.valid = true;
}
